/* ══════════════════════════════════════════════════════════════════════
   DER GRUNDSTOCK: 115 PROBLEME UND WIE MAN SIE LÖST

   Aus dem Betrieb, 22.9.2026, zusammen mit einer PDF:
     „ich gebe dir auch eine pdf mit 115 problemen und wie man sie löst
      und alles, kannst du mir dies schonmal eintragen das wir eine art
      grundbase haben."

   Quelle: „Körper Formen — Mitarbeiter-Handbuch, Problemlösungen &
   Arbeitsabläufe". 13 Kategorien, 115 Einträge, 564 Schritte. Aus der
   PDF gelesen, nicht abgetippt und nicht umformuliert — der Wortlaut
   ist der des Handbuchs.

   ── WARUM DAS EINE DATEI IST UND NICHT 115 DATENSÄTZE ──────────────
   Läge der Grundstock in der Datenbank, kostete er bei jedem Öffnen
   der Liste 115 Lesevorgänge — bei 39 Konten und ein paar Sitzungen am
   Tag sind das rund 10.000 am Tag, für Inhalte, die sich nie ändern.
   Das freie Kontingent liegt bei 50.000. Als Datei kostet er NICHTS,
   liegt im Browser-Zwischenspeicher und ist auch offline da.

   ── UND WIE MAN IHN TROTZDEM BEARBEITEN KANN ───────────────────────
   Wer einen Eintrag ändert oder ein Foto anhängt, legt damit einen
   EIGENEN Datensatz in `loesungen` an, der auf diesen hier zeigt
   (Feld `basis`). Die App zeigt dann den eigenen. Nur geänderte
   Einträge kosten also etwas — die übrigen 114 nicht.

   ── WAS HIER NICHT STEHT ───────────────────────────────────────────
   Keine Studio-Zuordnung: der Grundstock gilt überall. Keine
   Verfasser: er kommt aus dem Handbuch, nicht von einer Person. Wer
   ihn ändert, steht danach an seinem eigenen Eintrag.

   ── ÄNDERN ─────────────────────────────────────────────────────────
   Diese Datei wird NICHT von Hand gepflegt. Sie entsteht aus der PDF;
   wer sie ändert, ändert sie an der Quelle und erzeugt sie neu.
   ══════════════════════════════════════════════════════════════════ */
window.LOESUNGEN_BASIS = {
  stand: '2026-09-22',
  quelle: 'Körper Formen — Mitarbeiter-Handbuch, Problemlösungen & Arbeitsabläufe',
  eintraege: [
    {id:'b1',nr:1,kat:'kunde',titel:'Kunde kommt zu spät zum Termin',problem:'Der Kunde erscheint verspätet und der Terminplan gerät unter Druck.',schritte:['Kunden freundlich begrüßen.','Verspätungsdauer und nächsten Termin prüfen.','Wenn möglich Training normal durchführen, ohne den Folgetermin zu beeinträchtigen.','Bei stärkerer Verspätung erklären, dass sich die Trainingszeit verkürzen kann.','Falls der Termin nicht mehr sinnvoll durchführbar ist, nach Studio-Regeln verschieben.','Wiederholte Verspätungen dokumentieren und bei Bedarf Leitung informieren.'],stich:'kunde kommt spaet termin erscheint verspaetet terminplan geraet druck'},
    {id:'b2',nr:2,kat:'kunde',titel:'Kunde erscheint nicht zum Termin',problem:'Ein gebuchter Termin wird ohne vorherige Absage nicht wahrgenommen.',schritte:['Termin und Uhrzeit prüfen.','Angemessene Wartezeit einhalten.','Kunden nach Studio-Regeln kontaktieren.','Terminstatus aktualisieren.','Falls möglich frei gewordenen Termin neu vergeben.','Wiederholtes Nichterscheinen dokumentieren.'],stich:'kunde erscheint termin gebuchter vorherige absage wahrgenommen'},
    {id:'b3',nr:3,kat:'kunde',titel:'Kunde sagt kurzfristig ab',problem:'Ein Termin wird kurzfristig abgesagt und kann möglicherweise nicht mehr vergeben werden.',schritte:['Absage freundlich entgegennehmen.','Zeitpunkt der Absage prüfen.','Termin im System aktualisieren.','Stornoregeln des Studios beachten.','Wenn möglich Ersatztermin anbieten.','Bei wiederholten kurzfristigen Absagen Leitung informieren.'],stich:'kunde sagt kurzfristig termin abgesagt moeglicherweise vergeben'},
    {id:'b4',nr:4,kat:'kunde',titel:'Kunde möchte Termin verschieben',problem:'Ein bestehender Termin soll auf einen anderen Zeitpunkt verlegt werden.',schritte:['Aktuellen Termin öffnen.','Freie Zeiten prüfen.','Passende Alternativen anbieten.','Neuen Termin nach Bestätigung eintragen.','Alten Termin entfernen oder korrekt umsetzen.','Änderung dokumentieren.'],stich:'kunde moechte termin verschieben bestehender anderen zeitpunkt verlegt'},
    {id:'b5',nr:5,kat:'kunde',titel:'Kunde beschwert sich',problem:'Der Kunde ist mit Training, Betreuung oder Ablauf unzufrieden.',schritte:['Kunden ausreden lassen.','Konkreten Sachverhalt klären.','Ruhig und respektvoll reagieren.','Direkt lösbare Punkte sofort beheben.','Keine Schuldzuweisungen oder ungesicherten Versprechen.','Nicht selbst entscheidbare Fälle an die Leitung geben.','Beschwerde und Lösung dokumentieren.'],stich:'kunde beschwert training betreuung ablauf unzufrieden'},
    {id:'b6',nr:6,kat:'kunde',titel:'Kunde versteht eine Übung nicht',problem:'Der Kunde ist unsicher, wie eine Übung ausgeführt werden soll.',schritte:['Übung einfach erklären.','Bewegung vormachen.','Kunden selbst durchführen lassen.','Ausführung beobachten.','Fehler freundlich korrigieren.','Bei Bedarf Übung vereinfachen oder alternative Bewegung wählen.'],stich:'kunde versteht uebung unsicher ausgefuehrt'},
    {id:'b7',nr:7,kat:'kunde',titel:'Kunde führt Übung falsch aus',problem:'Eine Übung wird technisch unsauber oder unsicher durchgeführt.',schritte:['Übung bei relevantem Fehler unterbrechen.','Fehler konkret erklären.','Korrekte Position vormachen.','Kunden erneut ausführen lassen.','Ausführung kontrollieren.','Bei wiederholten Problemen Belastung oder Übung anpassen.'],stich:'kunde fuehrt uebung falsch technisch unsauber unsicher durchgefuehrt'},
    {id:'b8',nr:8,kat:'kunde',titel:'Kunde hat Schmerzen',problem:'Während einer Übung treten Schmerzen oder ungewöhnliche Beschwerden auf.',schritte:['Übung sofort unterbrechen.','Ort und Art der Beschwerden erfragen.','Nicht einfach weitermachen.','Belastung pausieren oder reduzieren.','Bei starken/anhaltenden Beschwerden nach Sicherheits- und Notfallvorgaben handeln.','Vorfall dokumentieren und Leitung informieren, wenn erforderlich.'],stich:'kunde schmerzen waehrend uebung treten ungewoehnliche beschwerden'},
    {id:'b9',nr:9,kat:'kunde',titel:'EMS-Intensität zu stark',problem:'Der Kunde empfindet die Stimulation als unangenehm stark.',schritte:['Kunden ernst nehmen.','Stimulation entsprechend der Gerätebedienung reduzieren.','Elektroden und Kontakt prüfen.','Kunden erneut nach Empfinden fragen.','Bei anhaltenden Beschwerden Training unterbrechen.','Technische Auffälligkeit dokumentieren.'],stich:'intensitaet stark kunde empfindet stimulation unangenehm'},
    {id:'b10',nr:10,kat:'kunde',titel:'EMS-Intensität zu schwach',problem:'Die Stimulation ist kaum oder gar nicht wahrnehmbar.',schritte:['Einstellungen prüfen.','Betroffene Muskelgruppe identifizieren.','Elektrodenposition und Kontakt prüfen.','Kabel und Steckverbindungen kontrollieren.','Intensität nach Trainingsvorgabe anpassen.','Bleibt das Problem bestehen, Gerät als Störung melden.'],stich:'intensitaet schwach stimulation kaum wahrnehmbar'},
    {id:'b11',nr:11,kat:'kunde',titel:'Kunde vergisst Handtuch/Sachen',problem:'Benötigte Trainingsausrüstung fehlt.',schritte:['Fehlendes Material feststellen.','Studio-Ersatz prüfen.','Falls vorhanden Ersatz ausgeben.','Kunden an benötigte Ausstattung erinnern.','Wiederholte Fälle freundlich ansprechen.'],stich:'kunde vergisst handtuch sachen benoetigte trainingsausruestung fehlt'},
    {id:'b12',nr:12,kat:'kunde',titel:'Frage zu Vertrag/Preis/Kündigung',problem:'Kunde fragt nach Vertragsbedingungen oder Kündigung.',schritte:['Frage genau aufnehmen.','Nur sichere Informationen geben.','Kundendaten/Vertrag prüfen, wenn berechtigt.','Bei Sonderfällen Leitung einbeziehen.','Keine eigenen Vertragszusagen machen.','Anfrage dokumentieren.'],stich:'frage vertrag preis kuendigung kunde fragt vertragsbedingungen'},
    {id:'b13',nr:13,kat:'kunde',titel:'Kunde möchte Trainingspause',problem:'Kunde möchte Training vorübergehend pausieren.',schritte:['Gewünschten Zeitraum erfragen.','Vertragliche Regelung prüfen.','Nur im eigenen Zuständigkeitsbereich bearbeiten.','Andernfalls an zuständige Person weiterleiten.','Kunden über nächsten Schritt informieren.','Änderung dokumentieren.'],stich:'kunde moechte trainingspause training voruebergehend pausieren'},
    {id:'b14',nr:14,kat:'kunde',titel:'Kunde möchte Zusatztermin',problem:'Kunde möchte außerhalb seiner regulären Termine trainieren.',schritte:['Wunsch aufnehmen.','Verfügbarkeit prüfen.','Termin auswählen.','Kosten/Regeln vorher klären, falls relevant.','Termin verbindlich eintragen.'],stich:'kunde moechte zusatztermin ausserhalb seiner regulaeren termine trainieren'},
    {id:'b15',nr:15,kat:'kunde',titel:'Begleitperson kommt mit',problem:'Ein Kunde erscheint mit einer nicht angemeldeten Begleitperson.',schritte:['Begleitperson freundlich begrüßen.','Grund des Besuchs klären.','Studio- und Sicherheitsregeln beachten.','Datenschutz und vertrauliche Kundendaten schützen.','Bei Unsicherheit Leitung fragen.'],stich:'begleitperson kommt kunde erscheint angemeldeten'},
    {id:'b16',nr:16,kat:'kunde',titel:'Neukunde kommt zum Probetraining',problem:'Ein Neukunde kennt Ablauf und Studio noch nicht.',schritte:['Termin prüfen und persönlich begrüßen.','Ablauf kurz erklären.','Notwendige Angaben/Unterlagen prüfen.','Umkleide und Trainingsbereich zeigen.','EMS-Ablauf erklären.','Training durchführen und regelmäßig nach Wohlbefinden fragen.','Nächste Schritte erklären.'],stich:'neukunde kommt probetraining kennt ablauf studio'},
    {id:'b17',nr:17,kat:'kunde',titel:'Kunde fühlt sich nicht betreut',problem:'Kunde empfindet die Betreuung während des Trainings als unzureichend.',schritte:['Feedback anhören.','Konkrete Ursache klären.','Aktiv beobachten und anleiten.','Regelmäßig nach Belastung fragen.','Ablauf bei Bedarf anpassen.','Feedback dokumentieren und bei Wiederholung Leitung informieren.'],stich:'kunde fuehlt betreut empfindet betreuung waehrend trainings unzureichend'},
    {id:'b18',nr:18,kat:'kunde',titel:'Kunde wartet zu lange',problem:'Ein Kunde muss trotz Termin warten.',schritte:['Kunden begrüßen und informieren.','Ursache kurz erklären.','Wartezeit realistisch einschätzen.','Bei längerer Verzögerung Alternative prüfen.','Ursache bei organisatorischem Problem dokumentieren.'],stich:'kunde wartet lange trotz termin warten'},
    {id:'b19',nr:19,kat:'kunde',titel:'Kunde möchte bestimmten Mitarbeiter',problem:'Kunde möchte bevorzugt von einer bestimmten Person trainiert werden.',schritte:['Wunsch aufnehmen.','Verfügbarkeit prüfen.','Termin entsprechend planen, wenn möglich.','Alternative anbieten, wenn nicht verfügbar.','Keine falschen Versprechen machen.'],stich:'kunde moechte bestimmten mitarbeiter bevorzugt person trainiert'},
    {id:'b20',nr:20,kat:'kunde',titel:'Kunde hinterlässt Bereich unsauber',problem:'Nach dem Training bleiben Müll, Handtücher oder Unordnung zurück.',schritte:['Bereich kontrollieren.','Müll entfernen.','Wäsche in vorgesehenen Behälter geben.','Fläche und Equipment reinigen.','Equipment ordentlich zurücklegen.','Bei wiederholtem Verhalten freundlich auf Regeln hinweisen.'],stich:'kunde hinterlaesst bereich unsauber training bleiben muell handtuecher unordnung zurueck'},
    {id:'b21',nr:21,kat:'geraet',titel:'Gerät lässt sich nicht einschalten',problem:'Ein EMS-Gerät startet nicht.',schritte:['Stromversorgung prüfen.','Netzteil/Ladezustand prüfen.','Verbindungen kontrollieren.','Nach Herstellervorgabe Neustart durchführen.','Nicht selbst öffnen oder reparieren.','Bei weiterem Fehler Gerät kennzeichnen und Störung melden.'],stich:'geraet laesst einschalten startet'},
    {id:'b22',nr:22,kat:'geraet',titel:'Elektrode funktioniert nicht',problem:'Eine Elektrode liefert keine oder unregelmäßige Stimulation.',schritte:['Kanal identifizieren.','Elektrode und Kontakt prüfen.','Kabel/Anschluss prüfen.','Position nach Trainingsstandard korrigieren.','Erneut testen.','Bei weiterem Fehler Gerät außer Betrieb nehmen bzw. melden.'],stich:'elektrode funktioniert liefert unregelmaessige stimulation'},
    {id:'b23',nr:23,kat:'geraet',titel:'Kabel beschädigt',problem:'Ein Kabel ist sichtbar beschädigt.',schritte:['Gerät nicht weiter benutzen, wenn Sicherheit betroffen sein könnte.','Beschädigung fotografieren.','Kabel kennzeichnen.','Leitung/Technik informieren.','Nur freigegebenes Ersatzteil verwenden.'],stich:'kabel beschaedigt sichtbar'},
    {id:'b24',nr:24,kat:'geraet',titel:'Kabel sitzt nicht richtig',problem:'Eine Verbindung ist locker.',schritte:['Training pausieren.','Steckverbindung prüfen.','Kabel korrekt nach Geräteanleitung verbinden.','Funktion kontrollieren.','Bei wiederholtem Lösen Kabel/Anschluss melden.'],stich:'kabel sitzt richtig verbindung locker'},
    {id:'b25',nr:25,kat:'geraet',titel:'Elektrode haftet nicht',problem:'Elektrode hat keinen ausreichenden Kontakt.',schritte:['Training pausieren.','Kontaktfläche und Elektrode prüfen.','Nach Hersteller-/Studioanweisung reinigen bzw. vorbereiten.','Elektrode korrekt positionieren.','Erneut testen.','Bei Verschleiß Austausch melden.'],stich:'elektrode haftet keinen ausreichenden kontakt'},
    {id:'b26',nr:26,kat:'geraet',titel:'Intensität lässt sich nicht einstellen',problem:'Bedienung reagiert nicht wie vorgesehen.',schritte:['Aktuelle Einstellung prüfen.','Betroffenen Kanal identifizieren.','Verbindung prüfen.','Software-/Gerätestatus prüfen.','Nur vorgesehenen Neustart durchführen.','Bei Fehler dokumentieren und melden.'],stich:'intensitaet laesst einstellen bedienung reagiert vorgesehen'},
    {id:'b27',nr:27,kat:'geraet',titel:'Gerät verliert Verbindung',problem:'Verbindung zwischen Komponenten bricht ab.',schritte:['Training sicher pausieren.','Kabel und Funk-/Verbindungsstatus prüfen.','Gerät nach Vorgabe neu verbinden.','Testlauf durchführen.','Wiederkehrende Ausfälle dokumentieren.'],stich:'geraet verliert verbindung zwischen komponenten bricht'},
    {id:'b28',nr:28,kat:'geraet',titel:'Software/App zeigt falsche Daten',problem:'Anwendung zeigt unerwartete Werte oder Status an.',schritte:['Anzeige dokumentieren/Screenshot erstellen.','App/Software nach Vorgabe neu starten.','Verbindung prüfen.','Nicht auf unsichere Werte vertrauen.','Fehler an zuständige Stelle melden.'],stich:'software zeigt falsche daten anwendung unerwartete werte status'},
    {id:'b29',nr:29,kat:'geraet',titel:'Akku leer',problem:'Ein benötigtes Gerät oder Zubehör hat keinen ausreichenden Akkustand.',schritte:['Ladezustand prüfen.','Geeignetes Ladegerät anschließen.','Ladevorgang kontrollieren.','Ersatzgerät verwenden, falls vorhanden.','Bei ungewöhnlich schnellem Entladen melden.'],stich:'akku leer benoetigtes geraet zubehoer keinen ausreichenden akkustand'},
    {id:'b30',nr:30,kat:'geraet',titel:'Ladegerät fehlt/defekt',problem:'Gerät kann nicht geladen werden.',schritte:['Prüfen, ob Ladegerät korrekt zugeordnet ist.','Andere freigegebene Ladequelle prüfen.','Defektes Ladegerät nicht weiter verwenden.','Ersatz anfordern.','Bestand aktualisieren.'],stich:'ladegeraet fehlt defekt geraet geladen'},
    {id:'b31',nr:31,kat:'geraet',titel:'Trainingsanzug beschädigt',problem:'EMS-Bekleidung weist Riss, Defekt oder starken Verschleiß auf.',schritte:['Nicht einfach weiterverwenden, wenn Funktion/Hygiene betroffen ist.','Defekt fotografieren.','Größe/Artikel dokumentieren.','Aussondern und Ersatz bereitstellen.','Austausch melden.'],stich:'trainingsanzug beschaedigt bekleidung weist riss defekt starken verschleiss'},
    {id:'b32',nr:32,kat:'geraet',titel:'Manschette/Gurt beschädigt',problem:'Ein Gurt oder eine Manschette ist verschlissen.',schritte:['Beschädigung prüfen.','Bei unsicherem Halt nicht einsetzen.','Aussondern.','Ersatz bereitstellen.','Bestand aktualisieren.'],stich:'manschette gurt beschaedigt verschlissen'},
    {id:'b33',nr:33,kat:'geraet',titel:'Gerät macht ungewöhnliche Geräusche',problem:'Während des Betriebs treten ungewöhnliche Geräusche auf.',schritte:['Training sicher stoppen.','Gerät ausschalten.','Nicht öffnen oder reparieren.','Geräusch und Situation dokumentieren.','Gerät kennzeichnen und prüfen lassen.'],stich:'geraet macht ungewoehnliche geraeusche waehrend betriebs treten'},
    {id:'b34',nr:34,kat:'geraet',titel:'Gerät wird ungewöhnlich warm',problem:'Ein Gerät oder Netzteil wird auffällig heiß.',schritte:['Betrieb sofort stoppen.','Stromversorgung nach Sicherheitsvorgabe trennen.','Gerät abkühlen lassen und nicht weiter benutzen.','Leitung/Technik informieren.','Vorfall dokumentieren.'],stich:'geraet ungewoehnlich warm netzteil auffaellig heiss'},
    {id:'b35',nr:35,kat:'geraet',titel:'Trainingszubehör fehlt',problem:'Benötigtes Zubehör ist nicht auffindbar.',schritte:['Zubehörliste prüfen.','Vorgesehenen Lagerplatz kontrollieren.','Bei anderem Raum nachfragen.','Fehlendes Teil als Bestandsthema melden.','Nachbestellung bzw. Ersatz veranlassen.'],stich:'trainingszubehoer fehlt benoetigtes zubehoer auffindbar'},
    {id:'b36',nr:36,kat:'hygiene',titel:'Trainingsplatz nach Training reinigen',problem:'Benutzte Trainingsfläche muss für den nächsten Kunden vorbereitet werden.',schritte:['Kundenmaterial entfernen.','Oberflächen nach Studio-/Herstellerangaben reinigen.','Gerät und Kontaktflächen reinigen.','Fläche trocken und ordentlich hinterlassen.','Reinigung bei Bedarf dokumentieren.'],stich:'trainingsplatz training reinigen benutzte trainingsflaeche fuer naechsten kunden vorbereitet'},
    {id:'b37',nr:37,kat:'hygiene',titel:'EMS-Equipment desinfizieren',problem:'Kontaktflächen und geeignetes Zubehör müssen hygienisch aufbereitet werden.',schritte:['Herstellerangaben desinfektionsverträglicher Materialien beachten.','Geeignetes Mittel verwenden.','Kontaktflächen vollständig bearbeiten.','Einwirkzeit beachten.','Vor Wiederverwendung vollständig trocknen lassen.'],stich:'equipment desinfizieren kontaktflaechen geeignetes zubehoer muessen hygienisch aufbereitet'},
    {id:'b38',nr:38,kat:'hygiene',titel:'Handtücher sammeln',problem:'Benutzte Handtücher müssen getrennt von sauberer Wäsche gesammelt werden.',schritte:['Benutzte Handtücher in vorgesehenen Behälter geben.','Nicht mit sauberer Wäsche vermischen.','Behälter bei Füllstand zur Wäsche weitergeben.','Bestand kontrollieren.'],stich:'handtuecher sammeln benutzte muessen getrennt sauberer waesche gesammelt'},
    {id:'b39',nr:39,kat:'hygiene',titel:'Boden verschmutzt',problem:'Trainingsfläche oder Boden ist verschmutzt.',schritte:['Bereich sichern, wenn Rutschgefahr besteht.','Verschmutzung entfernen.','Boden nach Studioangaben reinigen.','Trockenheit prüfen.','Ursache beseitigen, wenn möglich.'],stich:'boden verschmutzt trainingsflaeche'},
    {id:'b40',nr:40,kat:'hygiene',titel:'Spiegel verschmutzt',problem:'Spiegel weisen Schweiß, Fingerabdrücke oder Flecken auf.',schritte:['Geeignetes Reinigungsmittel verwenden.','Spiegel vollständig reinigen.','Streifen kontrollieren.','Reinigungsmittel nicht auf empfindliche Geräte sprühen.'],stich:'spiegel verschmutzt weisen schweiss fingerabdruecke flecken'},
    {id:'b41',nr:41,kat:'hygiene',titel:'Türklinken/Kontaktflächen reinigen',problem:'Häufig berührte Flächen müssen regelmäßig gereinigt werden.',schritte:['Reinigungsplan prüfen.','Geeignetes Mittel verwenden.','Klinken und Kontaktflächen vollständig bearbeiten.','Auf ausreichende Einwirkzeit achten.','Erledigung im Plan markieren.'],stich:'tuerklinken kontaktflaechen reinigen haeufig beruehrte flaechen muessen regelmaessig gereinigt'},
    {id:'b42',nr:42,kat:'hygiene',titel:'Umkleide reinigen',problem:'Umkleide soll sauber, trocken und ordentlich sein.',schritte:['Müll entfernen.','Bänke/Flächen reinigen.','Boden prüfen.','Vergessene Gegenstände sichern.','Mängel oder Schäden melden.'],stich:'umkleide reinigen sauber trocken ordentlich'},
    {id:'b43',nr:43,kat:'hygiene',titel:'Dusche reinigen',problem:'Duschen weisen Verschmutzungen oder Ablagerungen auf.',schritte:['Dusche kontrollieren.','Geeigneten Reiniger verwenden.','Flächen und Armaturen reinigen.','Abfluss prüfen.','Bereich trocken/ordentlich hinterlassen.','Schäden melden.'],stich:'dusche reinigen duschen weisen verschmutzungen ablagerungen'},
    {id:'b44',nr:44,kat:'hygiene',titel:'Waschbecken reinigen',problem:'Waschbecken und Armaturen müssen sauber sein.',schritte:['Oberflächen reinigen.','Armaturen abwischen.','Ablauf prüfen.','Wasserflecken entfernen.','Mittel sicher lagern.'],stich:'waschbecken reinigen armaturen muessen sauber'},
    {id:'b45',nr:45,kat:'hygiene',titel:'Toilette reinigen',problem:'Sanitärbereich muss hygienisch und funktionsfähig bleiben.',schritte:['Reinigungsplan prüfen.','Sanitärflächen reinigen.','Verbrauchsmaterial kontrollieren.','Boden prüfen.','Defekte oder Verstopfungen melden.'],stich:'toilette reinigen sanitaerbereich hygienisch funktionsfaehig bleiben'},
    {id:'b46',nr:46,kat:'hygiene',titel:'Mülleimer voll',problem:'Mülleimer muss geleert werden.',schritte:['Handschuhe nach Studiovorgabe verwenden.','Beutel schließen und entsorgen.','Neuen Beutel einsetzen.','Mülleimer bei Bedarf reinigen.','Abhol-/Entsorgungsregel beachten.'],stich:'muelleimer voll geleert'},
    {id:'b47',nr:47,kat:'hygiene',titel:'Reinigungsmittel leer',problem:'Ein benötigtes Reinigungsmittel ist nicht mehr vorhanden.',schritte:['Bestand prüfen.','Ersatz aus Lager holen, falls vorhanden.','Mindestbestand kontrollieren.','Nachbestellung melden.','Nicht eigenmächtig ungeeignete Mittel verwenden.'],stich:'reinigungsmittel leer benoetigtes vorhanden'},
    {id:'b48',nr:48,kat:'waesche',titel:'Zu wenig saubere Trainingswäsche',problem:'Der Vorrat reicht nicht für die geplanten Termine.',schritte:['Bestand zählen.','Tagesbedarf abschätzen.','Schmutzwäschebestand prüfen.','Waschvorgang priorisieren.','Bei dauerhaft niedrigem Bestand Leitung informieren.'],stich:'wenig saubere trainingswaesche vorrat reicht fuer geplanten termine'},
    {id:'b49',nr:49,kat:'waesche',titel:'Wäsche wurde nicht gewaschen',problem:'Schmutzwäsche wurde nicht bearbeitet.',schritte:['Wäschemenge prüfen.','Waschplan kontrollieren.','Passendes Programm nach Pflegeanweisung wählen.','Waschmittel korrekt dosieren.','Nach Ende weiterverarbeiten.'],stich:'waesche gewaschen schmutzwaesche bearbeitet'},
    {id:'b50',nr:50,kat:'waesche',titel:'Wäsche wurde vergessen',problem:'Wäsche liegt unbeachtet in Maschine oder Sammelbereich.',schritte:['Wäsche prüfen.','Wasch-/Trockenvorgang abschließen.','Nasse Wäsche nicht unnötig liegen lassen.','Status im Wäscheplan aktualisieren.'],stich:'waesche vergessen liegt unbeachtet maschine sammelbereich'},
    {id:'b51',nr:51,kat:'waesche',titel:'Wäsche noch nass',problem:'Wäsche ist nach dem Waschgang nicht trocken.',schritte:['Wäsche prüfen.','Geeigneten Trockenvorgang wählen.','Pflegehinweise beachten.','Nicht feucht in Schränke legen.','Bei Geruch/Feuchtigkeit erneut prüfen.'],stich:'waesche nass waschgang trocken'},
    {id:'b52',nr:52,kat:'waesche',titel:'Trockner ist voll',problem:'Trockner enthält fertige Wäsche und blockiert weitere Wäsche.',schritte:['Fertige Wäsche entnehmen.','Wäsche vollständig trocknen/abkühlen lassen.','Saubere Wäsche ordentlich lagern.','Trockner für nächsten Vorgang freigeben.'],stich:'trockner voll enthaelt fertige waesche blockiert weitere'},
    {id:'b53',nr:53,kat:'waesche',titel:'Waschmittel leer',problem:'Das Waschmittel reicht nicht mehr aus.',schritte:['Bestand prüfen.','Ersatz aus Lager verwenden.','Mindestbestand aktualisieren.','Nachbestellung melden.'],stich:'waschmittel leer reicht'},
    {id:'b54',nr:54,kat:'waesche',titel:'Falsches Waschprogramm',problem:'Wäsche wurde mit ungeeignetem Programm behandelt.',schritte:['Pflegeetikett/Studioanweisung prüfen.','Passendes Programm verwenden.','Bei Unsicherheit Leitung fragen.','Beschädigte Wäsche aussortieren und melden.'],stich:'falsches waschprogramm waesche ungeeignetem programm behandelt'},
    {id:'b55',nr:55,kat:'waesche',titel:'Saubere und schmutzige Wäsche vermischt',problem:'Hygienische Trennung ist nicht gewährleistet.',schritte:['Wäsche sofort trennen.','Saubere Wäsche nicht wieder in den Schmutzbereich legen.','Betroffene Wäsche bei Bedarf erneut waschen.','Lagerung klar kennzeichnen.'],stich:'saubere schmutzige waesche vermischt hygienische trennung gewaehrleistet'},
    {id:'b56',nr:56,kat:'waesche',titel:'Wäschebestand zu niedrig',problem:'Langfristig reicht der Bestand nicht für den Studiobetrieb.',schritte:['Bestand regelmäßig zählen.','Verbrauch dokumentieren.','Mindestbestand definieren.','Bei Unterschreitung Bestellung auslösen.','Lieferung kontrollieren.'],stich:'waeschebestand niedrig langfristig reicht bestand fuer studiobetrieb'},
    {id:'b57',nr:57,kat:'lager',titel:'Papierhandtücher leer',problem:'Im Sanitär- oder Arbeitsbereich fehlen Papierhandtücher.',schritte:['Bestand prüfen.','Ersatz auffüllen.','Mindestbestand kontrollieren.','Nachbestellung melden.'],stich:'papierhandtuecher leer sanitaer arbeitsbereich fehlen'},
    {id:'b58',nr:58,kat:'lager',titel:'Toilettenpapier leer',problem:'Sanitärbereich hat keinen ausreichenden Vorrat.',schritte:['Sofort Ersatzrolle einsetzen.','Lagerbestand prüfen.','Mindestbestand aktualisieren.','Nachbestellung auslösen.'],stich:'toilettenpapier leer sanitaerbereich keinen ausreichenden vorrat'},
    {id:'b59',nr:59,kat:'lager',titel:'Desinfektionsmittel leer',problem:'Benötigtes Hygienemittel fehlt.',schritte:['Bestand prüfen.','Geeignetes Ersatzmittel verwenden, falls freigegeben.','Nicht improvisieren.','Nachbestellung melden.'],stich:'desinfektionsmittel leer benoetigtes hygienemittel fehlt'},
    {id:'b60',nr:60,kat:'lager',titel:'Müllbeutel leer',problem:'Keine passenden Ersatzbeutel vorhanden.',schritte:['Lagerbestand prüfen.','Passende Beutel nachfüllen.','Mindestbestand prüfen.','Bestellung melden.'],stich:'muellbeutel leer passenden ersatzbeutel vorhanden'},
    {id:'b61',nr:61,kat:'lager',titel:'Handtuchbestand zu niedrig',problem:'Nicht genügend saubere Handtücher vorhanden.',schritte:['Bestand zählen.','Wäschekreislauf prüfen.','Waschvorgang priorisieren.','Bei dauerhaftem Engpass Bestand erhöhen.'],stich:'handtuchbestand niedrig genuegend saubere handtuecher vorhanden'},
    {id:'b62',nr:62,kat:'lager',titel:'Material falsch gelagert',problem:'Material liegt nicht am vorgesehenen Platz.',schritte:['Material identifizieren.','Richtigen Lagerplatz prüfen.','Material einsortieren.','Lagerplatz ggf. beschriften.','Fehlende Ordnung im Team ansprechen.'],stich:'material falsch gelagert liegt vorgesehenen platz'},
    {id:'b63',nr:63,kat:'lager',titel:'Material abgelaufen/beschädigt',problem:'Verbrauchsmaterial ist nicht mehr verwendbar.',schritte:['Artikel prüfen.','Nicht verwendbare Produkte aussortieren.','Entsorgung nach Vorgabe.','Bestand aktualisieren.','Ersatz beschaffen.'],stich:'material abgelaufen beschaedigt verbrauchsmaterial verwendbar'},
    {id:'b64',nr:64,kat:'lager',titel:'Lieferung kommt an',problem:'Neue Ware muss kontrolliert und eingeräumt werden.',schritte:['Lieferung mit Bestellung vergleichen.','Menge und Zustand prüfen.','Fehlmengen/Beschädigungen dokumentieren.','Ware richtig lagern.','Bestand aktualisieren.'],stich:'lieferung kommt neue ware kontrolliert eingeraeumt'},
    {id:'b65',nr:65,kat:'termin',titel:'Termin doppelt vergeben',problem:'Zwei Kunden wurden auf denselben Slot gebucht.',schritte:['Beide Buchungen prüfen.','Kundenkontakt freundlich aufnehmen.','Alternative Zeit anbieten.','System korrigieren.','Ursache dokumentieren, damit sie nicht wiederholt wird.'],stich:'termin doppelt vergeben zwei kunden wurden denselben slot gebucht'},
    {id:'b66',nr:66,kat:'termin',titel:'Termin wurde nicht abgesagt',problem:'Im System steht ein Termin, obwohl er anderweitig abgesprochen wurde.',schritte:['Kundenstatus prüfen.','Absage nachweisbar prüfen.','System aktualisieren.','Bei Unklarheit keine eigenmächtige Löschung vornehmen.'],stich:'termin abgesagt system steht obwohl anderweitig abgesprochen'},
    {id:'b67',nr:67,kat:'termin',titel:'Probetraining nicht vorbereitet',problem:'Neukunde erscheint, aber Informationen/Materialien fehlen.',schritte:['Termin prüfen.','Unterlagen/Einträge vorbereiten.','Trainingsplatz und Equipment kontrollieren.','Zuständige Person informieren, falls etwas fehlt.'],stich:'probetraining vorbereitet neukunde erscheint informationen materialien fehlen'},
    {id:'b68',nr:68,kat:'termin',titel:'Neukunde nicht im System',problem:'Kunde ist vor Ort, aber nicht korrekt angelegt.',schritte:['Identität/Termin prüfen.','Nur notwendige Daten aufnehmen.','Kundenprofil nach Studioablauf anlegen.','Datenschutz beachten.','Termin zuordnen.'],stich:'neukunde system kunde korrekt angelegt'},
    {id:'b69',nr:69,kat:'termin',titel:'Mitarbeiterausfall',problem:'Ein eingeplanter Mitarbeiter fällt kurzfristig aus.',schritte:['Termine und Schicht prüfen.','Leitung informieren.','Vertretung nach interner Regel suchen.','Betroffene Kunden informieren.','Änderungen dokumentieren.'],stich:'mitarbeiterausfall eingeplanter mitarbeiter faellt kurzfristig'},
    {id:'b70',nr:70,kat:'termin',titel:'Schicht nicht besetzt',problem:'Ein geplanter Zeitraum ist nicht ausreichend besetzt.',schritte:['Dienstplan prüfen.','Leitung informieren.','Vertretung organisieren.','Kundenbetreuung sicherstellen.','Ursache nachbereiten.'],stich:'schicht besetzt geplanter zeitraum ausreichend'},
    {id:'b71',nr:71,kat:'termin',titel:'Übergabe fehlt',problem:'Wichtige Informationen gehen zwischen Schichten verloren.',schritte:['Offene Aufgaben prüfen.','Kundenbesonderheiten und Störungen notieren.','Nächsten Mitarbeiter informieren.','Übergabe im System dokumentieren.'],stich:'uebergabe fehlt wichtige informationen gehen zwischen schichten verloren'},
    {id:'b72',nr:72,kat:'team',titel:'Aufgabe wurde nicht erledigt',problem:'Eine Aufgabe bleibt offen oder wird übersehen.',schritte:['Aufgabe im System prüfen.','Zuständigkeit klären.','Aufgabe übernehmen oder weitergeben.','Nach Erledigung Status aktualisieren.','Bei wiederholtem Problem Ursache klären.'],stich:'aufgabe erledigt bleibt offen uebersehen'},
    {id:'b73',nr:73,kat:'team',titel:'Aufgabe erledigt, aber nicht dokumentiert',problem:'Die Arbeit wurde erledigt, ist aber für andere nicht nachvollziehbar.',schritte:['Status nachträglich aktualisieren.','Kurz vermerken, was erledigt wurde.','Bei wiederkehrenden Aufgaben Checkliste verwenden.'],stich:'aufgabe erledigt dokumentiert arbeit fuer andere nachvollziehbar'},
    {id:'b74',nr:74,kat:'team',titel:'Kollege wusste nichts von Änderung',problem:'Eine relevante Information wurde nicht weitergegeben.',schritte:['Information sachlich nachreichen.','Kundendaten nur berechtigten Personen mitteilen.','Übergabe dokumentieren.','Bei wiederkehrendem Problem Kommunikationsweg verbessern.'],stich:'kollege wusste nichts aenderung relevante information weitergegeben'},
    {id:'b75',nr:75,kat:'team',titel:'Gerät nicht geladen',problem:'Ein Gerät wurde nach Nutzung nicht für den nächsten Einsatz vorbereitet.',schritte:['Ladezustand prüfen.','Freigegebenes Ladegerät anschließen.','Ladevorgang kontrollieren.','Nach Nutzung als Standardaufgabe dokumentieren.'],stich:'geraet geladen nutzung fuer naechsten einsatz vorbereitet'},
    {id:'b76',nr:76,kat:'team',titel:'Wäsche nicht weitergegeben',problem:'Wäsche wurde gesammelt, aber der nächste Arbeitsschritt nicht ausgelöst.',schritte:['Status prüfen.','Zuständigkeit klären.','Wäsche weitergeben.','Im Wäscheplan aktualisieren.'],stich:'waesche weitergegeben gesammelt naechste arbeitsschritt ausgeloest'},
    {id:'b77',nr:77,kat:'team',titel:'Kundenbeschwerde nicht weitergegeben',problem:'Ein relevanter Kundenhinweis erreicht die zuständige Person nicht.',schritte:['Beschwerde sachlich dokumentieren.','Zuständige Person informieren.','Rückmeldung/Status festhalten.','Kundenkontakt nachfassen, wenn vereinbart.'],stich:'kundenbeschwerde weitergegeben relevanter kundenhinweis erreicht zustaendige person'},
    {id:'b78',nr:78,kat:'team',titel:'Information steht nur in WhatsApp',problem:'Wichtige Betriebsinformation ist nur in einem privaten Chat vorhanden.',schritte:['Information in das offizielle System übertragen.','Verantwortliche Person festhalten.','Keine sensiblen Daten unnötig in private Chats kopieren.','WhatsApp nur als Ergänzung nutzen.'],stich:'information steht whatsapp wichtige betriebsinformation privaten chat vorhanden'},
    {id:'b79',nr:79,kat:'team',titel:'Mehrere Mitarbeiter bearbeiten dieselbe Aufgabe',problem:'Zuständigkeiten sind unklar.',schritte:['Aufgabe einmalig erfassen.','Verantwortliche Person festlegen.','Status zentral aktualisieren.','Doppelte Bearbeitung vermeiden.'],stich:'mehrere mitarbeiter bearbeiten dieselbe aufgabe zustaendigkeiten unklar'},
    {id:'b80',nr:80,kat:'gebaeude',titel:'Lampe defekt',problem:'Beleuchtung funktioniert nicht.',schritte:['Bereich prüfen.','Bei sicherer Zugänglichkeit Leuchtmittelproblem feststellen.','Nicht an elektrischen Anlagen improvisieren.','Defekt melden.','Bei sicherheitsrelevantem Ausfall Bereich absichern.'],stich:'lampe defekt beleuchtung funktioniert'},
    {id:'b81',nr:81,kat:'gebaeude',titel:'Steckdose funktioniert nicht',problem:'Eine Steckdose liefert keinen Strom oder wirkt beschädigt.',schritte:['Nicht weiter benutzen, wenn Beschädigung erkennbar ist.','Gerät trennen.','Bereich kennzeichnen.','Leitung/Technik informieren.','Keine eigene Elektroreparatur durchführen.'],stich:'steckdose funktioniert liefert keinen strom wirkt beschaedigt'},
    {id:'b82',nr:82,kat:'gebaeude',titel:'WLAN funktioniert nicht',problem:'Internetverbindung ist ausgefallen.',schritte:['Prüfen, ob nur ein Gerät oder das gesamte Studio betroffen ist.','Router/Verbindung nach interner Anleitung prüfen.','Geräte neu verbinden.','Bei Ausfall Leitung/Anbieter kontaktieren.'],stich:'wlan funktioniert internetverbindung ausgefallen'},
    {id:'b83',nr:83,kat:'gebaeude',titel:'Musik funktioniert nicht',problem:'Studio-Musik lässt sich nicht abspielen.',schritte:['Lautsprecher und Verbindung prüfen.','Quelle/Lautstärke kontrollieren.','Verbindung neu herstellen.','Bei technischem Defekt melden.'],stich:'musik funktioniert studio laesst abspielen'},
    {id:'b84',nr:84,kat:'gebaeude',titel:'Klimaanlage/Heizung funktioniert nicht',problem:'Raumtemperatur ist nicht wie vorgesehen.',schritte:['Einstellung prüfen.','Gerät nach Bedienungsanleitung prüfen.','Nicht eigenmächtig technische Abdeckungen öffnen.','Leitung informieren.','Bei unangemessener Raumtemperatur Trainingsbedingungen prüfen.'],stich:'klimaanlage heizung funktioniert raumtemperatur vorgesehen'},
    {id:'b85',nr:85,kat:'gebaeude',titel:'Dusche defekt',problem:'Dusche funktioniert nicht ordnungsgemäß.',schritte:['Art des Defekts feststellen.','Bei Wasserleck Bereich sichern.','Dusche ggf. außer Betrieb nehmen.','Leitung/Haustechnik informieren.','Kunden auf alternative Möglichkeit hinweisen.'],stich:'dusche defekt funktioniert ordnungsgemaess'},
    {id:'b86',nr:86,kat:'gebaeude',titel:'Wasserhahn tropft',problem:'Armatur verliert Wasser.',schritte:['Wasserverlust prüfen.','Bei starkem Leck Bereich sichern.','Nicht selbst reparieren, wenn keine Freigabe besteht.','Haus-/Studioleitung informieren.'],stich:'wasserhahn tropft armatur verliert wasser'},
    {id:'b87',nr:87,kat:'gebaeude',titel:'Tür klemmt',problem:'Tür lässt sich nicht normal öffnen oder schließen.',schritte:['Nicht mit Gewalt bewegen.','Prüfen, ob etwas blockiert.','Sicherheitsrelevante Einschränkung sofort melden.','Bei Bedarf Bereich kennzeichnen.'],stich:'tuer klemmt laesst normal oeffnen schliessen'},
    {id:'b88',nr:88,kat:'gebaeude',titel:'Möbel beschädigt',problem:'Schrank, Bank oder anderes Mobiliar ist beschädigt.',schritte:['Beschädigung fotografieren.','Nutzbarkeit prüfen.','Bei Verletzungsgefahr außer Betrieb nehmen.','Reparatur melden.'],stich:'moebel beschaedigt schrank bank anderes mobiliar'},
    {id:'b89',nr:89,kat:'gebaeude',titel:'Abfluss verstopft',problem:'Wasser läuft schlecht oder gar nicht ab.',schritte:['Bereich möglichst nicht weiter benutzen.','Überlaufen verhindern.','Keine ungeeigneten Chemikalien einsetzen.','Haus-/Studioleitung informieren.'],stich:'abfluss verstopft wasser laeuft schlecht'},
    {id:'b90',nr:90,kat:'sicherheit',titel:'Erste-Hilfe-Kasten unvollständig',problem:'Benötigtes Erste-Hilfe-Material fehlt.',schritte:['Bestand anhand Checkliste prüfen.','Fehlende Materialien dokumentieren.','Nachfüllung veranlassen.','Kontrolle regelmäßig durchführen.'],stich:'erste hilfe kasten unvollstaendig benoetigtes material fehlt'},
    {id:'b91',nr:91,kat:'sicherheit',titel:'Feuerlöscher/Brandschutz auffällig',problem:'Brandschutzausrüstung ist beschädigt, blockiert oder nicht korrekt zugänglich.',schritte:['Nicht verdecken oder verschieben, wenn dadurch Sicherheit beeinträchtigt wird.','Auffälligkeit dokumentieren.','Leitung informieren.','Prüfung durch zuständige Fachperson veranlassen.'],stich:'feuerloescher brandschutz auffaellig brandschutzausruestung beschaedigt blockiert korrekt zugaenglich'},
    {id:'b92',nr:92,kat:'sicherheit',titel:'Notausgang versperrt',problem:'Fluchtweg ist durch Gegenstände eingeschränkt.',schritte:['Hindernis sofort entfernen, wenn gefahrlos möglich.','Fluchtweg vollständig freihalten.','Ursache beseitigen.','Bei wiederholtem Problem im Team ansprechen.'],stich:'notausgang versperrt fluchtweg gegenstaende eingeschraenkt'},
    {id:'b93',nr:93,kat:'sicherheit',titel:'Kabel liegen herum',problem:'Kabel erzeugen Stolpergefahr.',schritte:['Training/Bewegungsbereich sichern.','Kabel ordentlich führen oder verstauen.','Defekte Kabel melden.','Regelmäßig kontrollieren.'],stich:'kabel liegen herum erzeugen stolpergefahr'},
    {id:'b94',nr:94,kat:'sicherheit',titel:'Flüssigkeit auf dem Boden',problem:'Verschüttete Flüssigkeit erzeugt Rutschgefahr.',schritte:['Bereich sofort sichern.','Flüssigkeit entfernen.','Boden trocknen.','Ursache feststellen.','Bei Schäden dokumentieren.'],stich:'fluessigkeit boden verschuettete erzeugt rutschgefahr'},
    {id:'b95',nr:95,kat:'sicherheit',titel:'Kunde fühlt sich plötzlich unwohl',problem:'Kunde meldet Schwindel, Übelkeit oder anderes akutes Unwohlsein.',schritte:['Training sofort pausieren.','Kunden sicher hinsetzen/lagern nach Situation.','Zustand beobachten und nach interner Notfallvorgabe handeln.','Bei medizinischem Notfall Rettungsdienst über 112 alarmieren.','Vorfall dokumentieren.','Leitung informieren.'],stich:'kunde fuehlt ploetzlich unwohl meldet schwindel uebelkeit anderes akutes unwohlsein'},
    {id:'b96',nr:96,kat:'sicherheit',titel:'Kunde verletzt sich',problem:'Es kommt zu einer Verletzung während des Aufenthalts.',schritte:['Training/Quelle der Gefahr stoppen.','Erste Hilfe im Rahmen der eigenen Qualifikation leisten.','Bei ernster Verletzung 112 rufen.','Bereich sichern.','Vorfall dokumentieren.','Leitung informieren.'],stich:'kunde verletzt kommt verletzung waehrend aufenthalts'},
    {id:'b97',nr:97,kat:'sicherheit',titel:'Mitarbeiter verletzt sich',problem:'Mitarbeiter verletzt sich während der Arbeit.',schritte:['Arbeit unterbrechen.','Erste Hilfe leisten bzw. Hilfe holen.','Bei Notfall 112.','Arbeitsunfall nach interner Vorgabe melden und dokumentieren.'],stich:'mitarbeiter verletzt waehrend arbeit'},
    {id:'b98',nr:98,kat:'datenschutz',titel:'Kundendaten werden falsch eingetragen',problem:'Daten im Kundensystem sind fehlerhaft.',schritte:['Fehler prüfen.','Nur berechtigte Änderungen durchführen.','Korrektur sachlich vornehmen.','Keine unnötigen Daten kopieren.','Bei Unsicherheit zuständige Person fragen.'],stich:'kundendaten falsch eingetragen daten kundensystem fehlerhaft'},
    {id:'b99',nr:99,kat:'datenschutz',titel:'Kundendaten werden vor Dritten besprochen',problem:'Vertrauliche Informationen könnten von Unbefugten gehört werden.',schritte:['Gespräch unterbrechen bzw. in geschützten Bereich verlagern.','Nur notwendige Informationen nennen.','Bildschirm/Unterlagen vor Einsicht schützen.','Bei Datenschutzvorfall Leitung informieren.'],stich:'kundendaten dritten besprochen vertrauliche informationen koennten unbefugten gehoert'},
    {id:'b100',nr:100,kat:'datenschutz',titel:'Falscher Kunde im System geöffnet',problem:'Ein Mitarbeiter hat versehentlich das falsche Kundenprofil geöffnet.',schritte:['Bearbeitung sofort stoppen.','Nicht benötigte Daten nicht weiter ansehen oder kopieren.','Richtiges Profil öffnen.','Bei Änderungen am falschen Profil Leitung informieren und Korrektur veranlassen.'],stich:'falscher kunde system geoeffnet mitarbeiter versehentlich falsche kundenprofil'},
    {id:'b101',nr:101,kat:'datenschutz',titel:'Kundendokument liegt offen herum',problem:'Papier mit personenbezogenen Daten ist frei zugänglich.',schritte:['Dokument sichern.','An vorgesehenem Ort ablegen.','Nicht fotografieren oder privat speichern.','Bei möglichem Datenschutzvorfall Leitung informieren.'],stich:'kundendokument liegt offen herum papier personenbezogenen daten frei zugaenglich'},
    {id:'b102',nr:102,kat:'datenschutz',titel:'Passwort/Account geteilt',problem:'Zugangsdaten werden gemeinsam verwendet.',schritte:['Keine Passwörter weitergeben.','Eigenen Zugang verwenden.','Geteilte Zugangsdaten nach interner Vorgabe ändern.','Bei Verdacht auf unbefugten Zugriff Leitung informieren.'],stich:'passwort account geteilt zugangsdaten gemeinsam verwendet'},
    {id:'b103',nr:103,kat:'verkauf',titel:'Kunde fragt nach Produkt/Leistung',problem:'Kunde möchte wissen, welche Leistung oder welches Angebot passt.',schritte:['Bedarf des Kunden erfragen.','Nur tatsächlich angebotene Leistungen erklären.','Preise und Vertragsbedingungen korrekt wiedergeben.','Keine medizinischen Versprechen machen.','Bei Sonderfällen Leitung einbeziehen.'],stich:'kunde fragt produkt leistung moechte wissen welche welches angebot passt'},
    {id:'b104',nr:104,kat:'verkauf',titel:'Kunde möchte sofort abschließen',problem:'Kunde möchte direkt einen Vertrag oder eine Leistung buchen.',schritte:['Produkt/Vertrag transparent erklären.','Preis, Laufzeit und relevante Bedingungen nennen.','Fragen beantworten.','Nur autorisierte Abschlussprozesse verwenden.','Kunde soll Entscheidung ohne Druck treffen.'],stich:'kunde moechte sofort abschliessen direkt vertrag leistung buchen'},
    {id:'b105',nr:105,kat:'verkauf',titel:'Kunde erwartet medizinische Beratung',problem:'Kunde fragt nach einer medizinischen Diagnose oder Therapieempfehlung.',schritte:['Keine Diagnose stellen.','Keine medizinischen Versprechen machen.','Auf Arzt/qualifizierte Fachperson verweisen, wenn angemessen.','Training nur innerhalb der Studio- und Sicherheitsvorgaben durchführen.'],stich:'kunde erwartet medizinische beratung fragt medizinischen diagnose therapieempfehlung'},
    {id:'b106',nr:106,kat:'verkauf',titel:'Kunde möchte Ergebnisgarantie',problem:'Kunde erwartet eine garantierte körperliche Veränderung.',schritte:['Keine Erfolgsgarantie geben.','Realistische, allgemeine Informationen geben.','Individuelle Ergebnisse als abhängig von mehreren Faktoren erklären.','Bei medizinischen Fragen Fachpersonal empfehlen.'],stich:'kunde moechte ergebnisgarantie erwartet garantierte koerperliche veraenderung'},
    {id:'b107',nr:107,kat:'routine',titel:'Studioöffnung nicht vollständig vorbereitet',problem:'Beim Öffnen fehlen Geräte, Sauberkeit oder Verbrauchsmaterial.',schritte:['Licht/Studiozugang prüfen.','Trainingsräume kontrollieren.','Geräte und Akkustände prüfen.','Sauberkeit prüfen.','Handtücher und Verbrauchsmaterial auffüllen.','Termine des Tages prüfen.','Besondere Hinweise lesen.'],stich:'studiooeffnung vollstaendig vorbereitet oeffnen fehlen geraete sauberkeit verbrauchsmaterial'},
    {id:'b108',nr:108,kat:'routine',titel:'Studio soll geschlossen werden',problem:'Am Tagesende müssen Räume und Technik sicher hinterlassen werden.',schritte:['Letzte Kunden verabschieden.','Trainingsbereiche kontrollieren.','Geräte nach Vorgabe ausschalten/laden.','Wäsche und Müll bearbeiten.','Sanitärbereiche prüfen.','Fenster/Türen nach Vorgabe prüfen.','Alarm-/Schließroutine durchführen.'],stich:'studio geschlossen tagesende muessen raeume technik sicher hinterlassen'},
    {id:'b109',nr:109,kat:'routine',titel:'Offene Aufgabe am Schichtende',problem:'Nicht alle Aufgaben konnten erledigt werden.',schritte:['Offene Aufgaben sammeln.','Priorität bestimmen.','Dringende Punkte noch erledigen.','Rest an nächste Schicht übergeben.','Übergabe dokumentieren.'],stich:'offene aufgabe schichtende aufgaben konnten erledigt'},
    {id:'b110',nr:110,kat:'routine',titel:'Schlüssel/Access fehlt',problem:'Mitarbeiter kann vorgesehenen Bereich nicht betreten oder schließen.',schritte:['Nicht versuchen, Schlösser zu umgehen.','Zuständige Person kontaktieren.','Vorfall dokumentieren.','Ersatzregel nach Studioablauf nutzen.'],stich:'schluessel access fehlt mitarbeiter vorgesehenen bereich betreten schliessen'},
    {id:'b111',nr:111,kat:'technik',titel:'App/Studio-Software reagiert nicht',problem:'Die für den Studioablauf benötigte Software funktioniert nicht.',schritte:['Prüfen, ob Internet vorhanden ist.','App/Programm neu starten.','Gerät neu starten, wenn freigegeben.','Fehlermeldung dokumentieren.','Bei weiterem Fehler Support/Leitung informieren.'],stich:'studio software reagiert fuer studioablauf benoetigte funktioniert'},
    {id:'b112',nr:112,kat:'technik',titel:'Termin-Synchronisation funktioniert nicht',problem:'Terminänderungen erscheinen nicht überall korrekt.',schritte:['Quelle der Buchung prüfen.','Synchronisationsstatus prüfen.','Nicht mehrfach buchen, bevor Status geklärt ist.','Screenshot/Fehlerzeit dokumentieren.','Support informieren.'],stich:'termin synchronisation funktioniert terminaenderungen erscheinen ueberall korrekt'},
    {id:'b113',nr:113,kat:'technik',titel:'Mitarbeiter kann Aufgabe nicht abschließen',problem:'Eine digitale Aufgabe lässt sich technisch nicht auf erledigt setzen.',schritte:['Eingaben prüfen.','App neu laden.','Aufgabe erneut öffnen.','Screenshot des Fehlers machen.','Technische Störung melden.','Aufgabe bei Bedarf vorübergehend manuell dokumentieren.'],stich:'mitarbeiter aufgabe abschliessen digitale laesst technisch erledigt setzen'},
    {id:'b114',nr:114,kat:'technik',titel:'Benachrichtigung fehlt',problem:'Mitarbeiter erhält keine erwartete Meldung.',schritte:['Benachrichtigungseinstellungen prüfen.','App-Berechtigungen prüfen.','Internetverbindung prüfen.','Aufgabe manuell kontrollieren.','Technischen Fehler melden, wenn Problem bleibt.'],stich:'benachrichtigung fehlt mitarbeiter erhaelt erwartete meldung'},
    {id:'b115',nr:115,kat:'technik',titel:'Foto/Datei lässt sich nicht hochladen',problem:'Beleg oder Foto kann nicht an ein Ticket angehängt werden.',schritte:['Dateigröße/Format prüfen.','Internetverbindung prüfen.','App neu laden.','Erneut versuchen.','Falls nötig Datei sicher zwischenspeichern und später hochladen.','Keine sensiblen Kundendaten in private Apps auslagern.'],stich:'foto datei laesst hochladen beleg ticket angehaengt'}
  ]
};
